apiVersion: v1
kind: Service
metadata:
  name: nginx-service-custom-clusterip
spec:
  type: ClusterIP
  # Below ip entered as random within range 10.96.0.0/12
  clusterIP: 10.96.10.10
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80